import 'package:flutter/material.dart';
import 'package:seniguard/check_list.dart';

void main() {
  runApp(const Page_Add_List());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class Page_Add_List extends StatelessWidget {
  const Page_Add_List({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          AddList(),
        ]),
      ),
    );
  }
}

class AddList extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    // 기본 디자인 크기
    final double baseWidth = 1080;
    final double baseHeight = 1920;

    // 현재 화면 크기
    final Size screenSize = MediaQuery.of(context).size;

    // 기준 스케일 계산
    final double scale = screenSize.width / baseWidth; // 가로 기준 비율만 사용

    return Center(
      child: Container(
        width: baseWidth * scale, // 화면 너비에 맞춘 크기
        height: baseHeight * scale, // 비율에 맞춘 높이
        clipBehavior: Clip.antiAlias,
        decoration: ShapeDecoration(
          color: Colors.white,
          shape: RoundedRectangleBorder(
            side: BorderSide(
              width: 1,
              strokeAlign: BorderSide.strokeAlignCenter,
              color: const Color(0xFF53B175),
            ),
          ),
        ),
        child: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center, // 세로 방향 중앙 정렬
            crossAxisAlignment: CrossAxisAlignment.center, // 가로 방향 중앙 정렬
            children: [
              // 시간 텍스트
              Text(
                '시간',
                style: TextStyle(
                  color: Colors.black,
                  fontSize: 60 * scale,
                  fontFamily: 'Freesentation',
                  fontWeight: FontWeight.w600,
                ),
              ),
              const SizedBox(height: 20), // 간격
              // 시간 표시 컨테이너
              Container(
                width: 670 * scale,
                height: 140 * scale,
                decoration: ShapeDecoration(
                  color: const Color(0xFFD9D9D9),
                  shape: RoundedRectangleBorder(
                    borderRadius: BorderRadius.circular(30),
                  ),
                ),
                child: Center(
                  child: Text(
                    '오전 11:34',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 80 * scale,
                      fontFamily: 'Freesentation',
                      fontWeight: FontWeight.w900,
                    ),
                  ),
                ),
              ),
              const SizedBox(height: 50), // 간격
              // 작업 텍스트
              Text(
                '오늘 할일',
                style: TextStyle(
                  color: Colors.black,
                  fontSize: 70 * scale,
                  fontFamily: 'Freesentation',
                  fontWeight: FontWeight.w600,
                ),
              ),
              const SizedBox(height: 20), // 간격

              // 할일 텍스트 입력 컨테이너
              Container(
                width: 670 * scale,
                height: 593 * scale,
                decoration: ShapeDecoration(
                  color: const Color(0xFFD9D9D9),
                  shape: RoundedRectangleBorder(
                    borderRadius: BorderRadius.circular(30),
                  ),
                ),
                child: Center(
                  child: TextField(
                    textAlign: TextAlign.center, // 텍스트 중앙 정렬
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 70 * scale,
                      fontFamily: 'Freesentation',
                      fontWeight: FontWeight.w600,
                    ),
                    decoration: InputDecoration(
                      hintText: '할 일을 입력하세요', // 기본 안내 텍스트
                      hintStyle: TextStyle(
                        color: Colors.grey,
                        fontSize: 70 * scale,
                      ),
                      border: InputBorder.none, // 입력창 테두리 제거
                      contentPadding: EdgeInsets.zero, // 여백 제거
                    ),
                  ),
                ),
              ),
              const SizedBox(height: 50), // 간격
              // 하단 버튼
              Row(
                mainAxisAlignment: MainAxisAlignment.center, // 중앙 정렬
                children: [
                  // 왼쪽 버튼
                  Container(
                    width: 200 * scale,
                    height: 200 * scale,
                    decoration: ShapeDecoration(
                      color: Colors.white,
                      shape: RoundedRectangleBorder(
                        borderRadius: BorderRadius.circular(4),
                      ),
                    ),
                    child: Center(
                      child: GestureDetector(
                        onTap: () {
                          // 버튼 클릭 시 새 화면으로 이동
                          Navigator.push(
                            context,
                            MaterialPageRoute(
                              builder: (context) => const Page_CheckList(),
                            ),
                          );
                        },
                        child: Container(
                          width: 175 * scale,
                          height: 175 * scale,
                          decoration: ShapeDecoration(
                            color: const Color(0xFFEA4335),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(705.88),
                            ),
                          ),
                          child: const Icon(
                            Icons.close, // 다른 아이콘 (예: 플러스)
                            color: Colors.white,
                          ),
                        ),
                      ),
                    ),
                  ),
                  const SizedBox(width: 20), // 버튼 간의 간격
                  // 기존 오른쪽 버튼
                  Container(
                    width: 200 * scale,
                    height: 200 * scale,
                    decoration: ShapeDecoration(
                      color: Colors.white,
                      shape: RoundedRectangleBorder(
                        borderRadius: BorderRadius.circular(4),
                      ),
                    ),
                    child: Center(
                      child: Container(
                        width: 175 * scale,
                        height: 175 * scale,
                        decoration: ShapeDecoration(
                          color: const Color(0xFF53B175),
                          shape: RoundedRectangleBorder(
                            borderRadius: BorderRadius.circular(705.88),
                          ),
                        ),
                        child: const Icon(
                          Icons.check, // 기존 아이콘 (체크)
                          color: Colors.white,
                        ),
                      ),
                    ),
                  ),
                ],
              )
            ],
          ),
        ),
      ),
    );
  }
}
