import 'package:flutter/material.dart';
import 'package:seniguard/chat_bot.dart';
// import 'package:seniguard/chat.dart';

void main() {
  runApp(const FigmaToCode_2());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCode_2 extends StatelessWidget {
  const FigmaToCode_2({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          SelectPage(),
        ]),
      ),
    );
  }
}

class SelectPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 1080,
          height: 1920,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(color: Colors.white),
          child: Stack(
            children: [
              Positioned(
                left: -70,
                top: 331,
                child: Container(
                  width: 1231,
                  height: 1593,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://via.placeholder.com/1231x1593"),
                      fit: BoxFit.fill,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 0,
                child: Container(
                  width: 1080,
                  height: 75,
                  decoration: BoxDecoration(color: Color(0xFF53B175)),
                ),
              ),
              Positioned(
                left: 72,
                top: 136,
                child: SizedBox(
                  width: 520,
                  child: Text(
                    '오늘 하루는 어떠신가요 ?',
                    style: TextStyle(
                      color: Color(0xFF3F414E),
                      fontSize: 60,
                      fontFamily: 'Freesentation',
                      fontWeight: FontWeight.w400,
                      height: 0.02,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 130,
                top: 198,
                child: Text(
                  'can choose what you want to do:',
                  style: TextStyle(
                    color: Color(0xFFA1A4B2),
                    fontSize: 30,
                    fontFamily: 'Freesentation',
                    fontWeight: FontWeight.w400,
                    height: 0,
                  ),
                ),
              ),
              Positioned(
                left: 853,
                top: 117,
                child: SizedBox(
                  width: 169,
                  child: Text(
                    '11:35 ',
                    style: TextStyle(
                      color: Color(0xFF3F414E),
                      fontSize: 60,
                      fontFamily: 'Freesentation',
                      fontWeight: FontWeight.w400,
                      height: 0.02,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: -88.70,
                top: 987.86,
                child: Container(
                  width: 1296.52,
                  height: 1092.86,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://via.placeholder.com/1297x1093"),
                      fit: BoxFit.fill,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: -70.43,
                top: 1540.71,
                child: Container(
                  width: 1184.35,
                  height: 529.29,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 100.71,
                        child: Container(
                          width: 313.04,
                          height: 428.57,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 171.43,
                                child: Container(
                                  width: 313.04,
                                  height: 257.14,
                                  child: Stack(),
                                ),
                              ),
                              Positioned(
                                left: 41.74,
                                top: 244.29,
                                child: Container(
                                  width: 112.17,
                                  height: 92.14,
                                  child: FlutterLogo(),
                                ),
                              ),
                              Positioned(
                                left: 169.57,
                                top: 214.29,
                                child: Container(
                                  width: 91.30,
                                  height: 75,
                                  child: FlutterLogo(),
                                ),
                              ),
                              Positioned(
                                left: 31.30,
                                top: -8.57,
                                child: Container(
                                  width: 250.43,
                                  height: 205.71,
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: -6.53,
                                        top: -0.14,
                                        child: Container(
                                          width: 264.24,
                                          height: 207.57,
                                          child: Stack(
                                            children: [
                                              Positioned(
                                                left: 90,
                                                top: 0.14,
                                                child: Container(
                                                  width: 83.48,
                                                  height: 205.71,
                                                  child: FlutterLogo(),
                                                ),
                                              ),
                                              Positioned(
                                                left: 0.26,
                                                top: 103,
                                                child: Transform(
                                                  transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(-1.19),
                                                  child: Container(
                                                    width: 70.13,
                                                    height: 246.51,
                                                    child: FlutterLogo(),
                                                  ),
                                                ),
                                              ),
                                              Positioned(
                                                left: 92.09,
                                                top: 207.57,
                                                child: Transform(
                                                  transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(-2.60),
                                                  child: Container(
                                                    width: 78.65,
                                                    height: 222.18,
                                                    child: FlutterLogo(),
                                                  ),
                                                ),
                                              ),
                                              Positioned(
                                                left: 240.26,
                                                top: 166.43,
                                                child: Transform(
                                                  transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(2.60),
                                                  child: Container(
                                                    width: 78.65,
                                                    height: 222.18,
                                                    child: FlutterLogo(),
                                                  ),
                                                ),
                                              ),
                                              Positioned(
                                                left: 238.18,
                                                top: 37.85,
                                                child: Transform(
                                                  transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(1.19),
                                                  child: Container(
                                                    width: 70.13,
                                                    height: 246.51,
                                                    child: FlutterLogo(),
                                                  ),
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 57.42,
                                        top: -10.24,
                                        child: Transform(
                                          transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(0.27),
                                          child: Container(
                                            width: 213.35,
                                            height: 182.69,
                                            child: FlutterLogo(),
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 232.17,
                        top: 0,
                        child: Container(
                          width: 313.04,
                          height: 428.57,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 171.43,
                                child: Container(
                                  width: 313.04,
                                  height: 257.14,
                                  child: Stack(),
                                ),
                              ),
                              Positioned(
                                left: 137.90,
                                top: 214.92,
                                child: Transform(
                                  transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(2.70),
                                  child: Container(
                                    width: 142.52,
                                    height: 129.29,
                                    child: Stack(
                                      children: [
                                        Positioned(
                                          left: 22.56,
                                          top: 0,
                                          child: Container(
                                            width: 97.39,
                                            height: 56.02,
                                            child: Stack(
                                              children: [
                                                Positioned(
                                                  left: 3.56,
                                                  top: 9.70,
                                                  child: Container(
                                                    width: 5.94,
                                                    height: 5.39,
                                                    decoration: ShapeDecoration(
                                                      color: Color(0xFFFB5D66),
                                                      shape: OvalBorder(),
                                                    ),
                                                  ),
                                                ),
                                                Positioned(
                                                  left: 22.56,
                                                  top: 15.08,
                                                  child: Container(
                                                    width: 5.94,
                                                    height: 5.39,
                                                    decoration: ShapeDecoration(
                                                      color: Color(0xFFFB5D66),
                                                      shape: OvalBorder(),
                                                    ),
                                                  ),
                                                ),
                                                Positioned(
                                                  left: 38,
                                                  top: 21.55,
                                                  child: Container(
                                                    width: 5.94,
                                                    height: 5.39,
                                                    decoration: ShapeDecoration(
                                                      color: Color(0xFFFB5D66),
                                                      shape: OvalBorder(),
                                                    ),
                                                  ),
                                                ),
                                                Positioned(
                                                  left: 89.07,
                                                  top: 34.48,
                                                  child: Container(
                                                    width: 5.94,
                                                    height: 5.39,
                                                    decoration: ShapeDecoration(
                                                      color: Color(0xFFFB5D66),
                                                      shape: OvalBorder(),
                                                    ),
                                                  ),
                                                ),
                                                Positioned(
                                                  left: 91.45,
                                                  top: 43.10,
                                                  child: Container(
                                                    width: 5.94,
                                                    height: 5.39,
                                                    decoration: ShapeDecoration(
                                                      color: Color(0xFFFB5D66),
                                                      shape: OvalBorder(),
                                                    ),
                                                  ),
                                                ),
                                                Positioned(
                                                  left: 15.44,
                                                  top: 40.94,
                                                  child: Container(
                                                    width: 5.94,
                                                    height: 5.39,
                                                    decoration: ShapeDecoration(
                                                      color: Color(0xFFFB5D66),
                                                      shape: OvalBorder(),
                                                    ),
                                                  ),
                                                ),
                                                Positioned(
                                                  left: 16.63,
                                                  top: 50.64,
                                                  child: Container(
                                                    width: 5.94,
                                                    height: 5.39,
                                                    decoration: ShapeDecoration(
                                                      color: Color(0xFFFB5D66),
                                                      shape: OvalBorder(),
                                                    ),
                                                  ),
                                                ),
                                                Positioned(
                                                  left: 0,
                                                  top: 16.16,
                                                  child: Container(
                                                    width: 7.13,
                                                    height: 6.46,
                                                    decoration: ShapeDecoration(
                                                      color: Color(0xFFFB5D66),
                                                      shape: OvalBorder(),
                                                    ),
                                                  ),
                                                ),
                                                Positioned(
                                                  left: 78.38,
                                                  top: 0,
                                                  child: Container(
                                                    width: 5.94,
                                                    height: 5.39,
                                                    decoration: ShapeDecoration(
                                                      color: Color(0xFFFB5D66),
                                                      shape: OvalBorder(),
                                                    ),
                                                  ),
                                                ),
                                                Positioned(
                                                  left: 89.07,
                                                  top: 1.08,
                                                  child: Container(
                                                    width: 5.94,
                                                    height: 5.39,
                                                    decoration: ShapeDecoration(
                                                      color: Color(0xFFFB5D66),
                                                      shape: OvalBorder(),
                                                    ),
                                                  ),
                                                ),
                                              ],
                                            ),
                                          ),
                                        ),
                                      ],
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 31.30,
                                top: 0,
                                child: Container(
                                  width: 250.43,
                                  height: 205.71,
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 0,
                                        top: 0,
                                        child: Container(
                                          width: 250.43,
                                          height: 205.71,
                                          child: FlutterLogo(),
                                        ),
                                      ),
                                      Positioned(
                                        left: 0,
                                        top: 0,
                                        child: Container(
                                          width: 250.43,
                                          height: 205.71,
                                          child: FlutterLogo(),
                                        ),
                                      ),
                                      Positioned(
                                        left: 0,
                                        top: 0,
                                        child: Container(
                                          width: 250.43,
                                          height: 205.71,
                                          child: FlutterLogo(),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 0,
                                top: 218.07,
                                child: Transform(
                                  transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(-0.44),
                                  child: Container(
                                    width: 78.85,
                                    height: 70.18,
                                    child: Stack(
                                      children: [
                                        Positioned(
                                          left: 0,
                                          top: 0,
                                          child: Container(
                                            width: 78.85,
                                            height: 70.18,
                                            child: FlutterLogo(),
                                          ),
                                        ),
                                        Positioned(
                                          left: 0,
                                          top: 0,
                                          child: Container(
                                            width: 78.85,
                                            height: 70.18,
                                            child: FlutterLogo(),
                                          ),
                                        ),
                                        Positioned(
                                          left: 0,
                                          top: 0,
                                          child: Container(
                                            width: 78.85,
                                            height: 70.18,
                                            child: FlutterLogo(),
                                          ),
                                        ),
                                      ],
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 299.96,
                                top: 216.43,
                                child: Transform(
                                  transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(3.12),
                                  child: Container(
                                    width: 169.55,
                                    height: 139.30,
                                    child: FlutterLogo(),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 871.30,
                        top: 19.29,
                        child: Container(
                          width: 313.04,
                          height: 428.57,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 171.43,
                                child: Container(
                                  width: 313.04,
                                  height: 257.14,
                                  child: Stack(),
                                ),
                              ),
                              Positioned(
                                left: 99.13,
                                top: 252.86,
                                child: Container(
                                  width: 213.91,
                                  height: 175.71,
                                  child: FlutterLogo(),
                                ),
                              ),
                              Positioned(
                                left: 31.30,
                                top: 312.86,
                                child: Container(
                                  width: 140.87,
                                  height: 115.71,
                                  child: FlutterLogo(),
                                ),
                              ),
                              Positioned(
                                left: 85.86,
                                top: -25.71,
                                child: Transform(
                                  transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(0.29),
                                  child: Container(
                                    width: 245.60,
                                    height: 211.46,
                                    child: Stack(
                                      children: [
                                        Positioned(
                                          left: 0,
                                          top: 0,
                                          child: Container(
                                            width: 245.60,
                                            height: 211.46,
                                            child: FlutterLogo(),
                                          ),
                                        ),
                                        Positioned(
                                          left: 0,
                                          top: 0,
                                          child: Container(
                                            width: 245.60,
                                            height: 211.46,
                                            child: FlutterLogo(),
                                          ),
                                        ),
                                        Positioned(
                                          left: 0,
                                          top: 0,
                                          child: Container(
                                            width: 245.60,
                                            height: 211.46,
                                            child: FlutterLogo(),
                                          ),
                                        ),
                                      ],
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 52.17,
                                top: 186.43,
                                child: Container(
                                  width: 106.96,
                                  height: 87.86,
                                  child: FlutterLogo(),
                                ),
                              ),
                              Positioned(
                                left: 185.53,
                                top: 195,
                                child: Transform(
                                  transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(0.22),
                                  child: Container(
                                    width: 100.87,
                                    height: 85.12,
                                    child: FlutterLogo(),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: -203.48,
                                top: 62.14,
                                child: Container(
                                  width: 313.04,
                                  height: 428.57,
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 0,
                                        top: 171.43,
                                        child: Container(
                                          width: 313.04,
                                          height: 257.14,
                                          child: Stack(),
                                        ),
                                      ),
                                      Positioned(
                                        left: 80.87,
                                        top: 214.29,
                                        child: Container(
                                          width: 78.26,
                                          height: 64.29,
                                          child: FlutterLogo(),
                                        ),
                                      ),
                                      Positioned(
                                        left: 180.83,
                                        top: 190.71,
                                        child: Transform(
                                          transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(0.22),
                                          child: Container(
                                            width: 242.41,
                                            height: 204.55,
                                            child: FlutterLogo(),
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 166.96,
                                        top: 197.14,
                                        child: Container(
                                          width: 54.78,
                                          height: 45,
                                          child: FlutterLogo(),
                                        ),
                                      ),
                                      Positioned(
                                        left: 44.35,
                                        top: 0,
                                        child: Container(
                                          width: 250.43,
                                          height: 205.71,
                                          child: Stack(
                                            children: [
                                              Positioned(
                                                left: 0,
                                                top: 0,
                                                child: Container(
                                                  width: 250.43,
                                                  height: 205.71,
                                                  child: FlutterLogo(),
                                                ),
                                              ),
                                              Positioned(
                                                left: 0,
                                                top: 0,
                                                child: Container(
                                                  width: 250.43,
                                                  height: 205.71,
                                                  child: FlutterLogo(),
                                                ),
                                              ),
                                              Positioned(
                                                left: 0,
                                                top: 0,
                                                child: Container(
                                                  width: 250.43,
                                                  height: 205.71,
                                                  child: FlutterLogo(),
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                              Positioned(
                                left: -229.87,
                                top: 45,
                                child: Container(
                                  width: 450,
                                  height: 150,
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 0,
                                        top: 0,
                                        child: Container(
                                          width: 450,
                                          height: 150,
                                          decoration: ShapeDecoration(
                                            color: Color(0xFF9B9B9B),
                                            shape: RoundedRectangleBorder(
                                              borderRadius: BorderRadius.circular(10),
                                            ),
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 72,
                top: 934,
                child: Container(
                  width: 450,
                  height: 600,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 450,
                          height: 600,
                          decoration: ShapeDecoration(
                            color: Color(0xFFEFCEFE),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(10),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 108,
                        top: 442,
                        child: SizedBox(
                          width: 239,
                          height: 91,
                          child: Text(
                            '산책 하기',
                            style: TextStyle(
                              color: Color(0xFFFDF9F3),
                              fontSize: 70,
                              fontFamily: 'Freesentation',
                              fontWeight: FontWeight.w600,
                              height: 0.01,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),

              // 챗봇 이동 버튼
              Positioned(
  left: 74,
  top: 261,
  child: GestureDetector(
    onTap: () {
      // 네비게이션 동작
      Navigator.push(
        context,
        MaterialPageRoute(builder: (context) => FigmaToCode_3()),
      );
    },
    child: Container(
      width: 450,
      height: 600,
      child: Stack(
        children: [
          Positioned(
            left: 0,
            top: 0,
            child: Container(
              width: 450,
              height: 600,
              decoration: ShapeDecoration(
                color: Color(0xFFF05D48),
                shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.circular(10),
                ),
              ),
            ),
          ),
          Positioned(
            left: 105,
            top: 446,
            child: SizedBox(
              width: 241,
              height: 91,
              child: Text(
                '시니 대화',
                style: TextStyle(
                  color: Color(0xFFFDF9F3),
                  fontSize: 70,
                  fontFamily: 'Freesentation',
                  fontWeight: FontWeight.w600,
                  height: 0.01,
                ),
              ),
            ),
          ),
        ],
      ),
    ),
  ),
),
// 챗봇 이동 버튼

              Positioned(
                left: 574,
                top: 261,
                child: Container(
                  width: 450,
                  height: 600,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 450,
                          height: 600,
                          decoration: ShapeDecoration(
                            color: Color(0xFFF9CF88),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(10),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 93,
                        top: 446,
                        child: SizedBox(
                          width: 278,
                          height: 91,
                          child: Text(
                            '체크리스트',
                            style: TextStyle(
                              color: Color(0xFFFDF9F3),
                              fontSize: 70,
                              fontFamily: 'Freesentation',
                              fontWeight: FontWeight.w600,
                              height: 0.01,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 574,
                top: 934,
                child: Container(
                  width: 450,
                  height: 600,
                  decoration: ShapeDecoration(
                    color: Color(0xFFF9CF88),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(10),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 580,
                top: 261,
                child: Container(
                  width: 442,
                  height: 401,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(),
                  child: Stack(),
                ),
              ),
              Positioned(
                left: 74,
                top: 995,
                child: Container(
                  width: 446,
                  height: 353,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(),
                  child: Stack(),
                ),
              ),
              Positioned(
                left: 58,
                top: 313,
                child: Container(
                  width: 444,
                  height: 379,
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.start,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    children: [
                      Container(
                        width: 487,
                        height: 262,
                        clipBehavior: Clip.antiAlias,
                        decoration: BoxDecoration(),
                        child: Stack(
                          children: [
                            Positioned(
                              left: 0,
                              top: 0,
                              child: Container(
                                width: 487,
                                height: 262,
                                child: Stack(
                                  children: [
                                    Positioned(
                                      left: 0,
                                      top: 0,
                                      child: Container(
                                        width: 487,
                                        height: 262,
                                        child: Stack(),
                                      ),
                                    ),
                                  ],
                                ),
                              ),
                            ),
                          ],
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}