import 'package:flutter/material.dart';
import 'package:seniguard/chat_bot.dart';

void main() {
  runApp(const FigmaToCode_2());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCode_2 extends StatelessWidget {
  const FigmaToCode_2({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          SelectPage(),
        ]),
      ),
    );
  }
}

class SelectPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 414,
          height: 896,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(color: Colors.white),
          child: Stack(
            children: [
              Positioned(
                left: -29,
                top: 107,
                child: Container(
                  width: 486,
                  height: 755,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image:
                          NetworkImage("https://via.placeholder.com/486x755"),
                      fit: BoxFit.fill,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: -17,
                child: Container(
                  width: 414,
                  height: 74,
                  decoration: BoxDecoration(color: Color(0xFF53B175)),
                ),
              ),
              Positioned(
                left: 20,
                top: 139,
                child: SizedBox(
                  width: 243,
                  child: Text(
                    '오늘 하루는 어떠신가요 ?',
                    style: TextStyle(
                      color: Color(0xFF3F414E),
                      fontSize: 28,
                      fontFamily: 'Freesentation',
                      fontWeight: FontWeight.w400,
                      height: 0.05,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 20,
                top: 177,
                child: Text(
                  'can choose what you want to do:',
                  style: TextStyle(
                    color: Color(0xFFA1A4B2),
                    fontSize: 20,
                    fontFamily: 'Freesentation',
                    fontWeight: FontWeight.w400,
                    height: 0,
                  ),
                ),
              ),
              Positioned(
                left: 20,
                top: 92,
                child: SizedBox(
                  width: 243,
                  child: Text(
                    '11:35 ',
                    style: TextStyle(
                      color: Color(0xFF3F414E),
                      fontSize: 28,
                      fontFamily: 'Freesentation',
                      fontWeight: FontWeight.w400,
                      height: 0.05,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: -34,
                top: 461,
                child: Container(
                  width: 497,
                  height: 510,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image:
                          NetworkImage("https://via.placeholder.com/497x510"),
                      fit: BoxFit.fill,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: -27,
                top: 719,
                child: Container(
                  width: 454,
                  height: 247,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 47,
                        child: Container(
                          width: 120,
                          height: 200,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 80,
                                child: Container(
                                  width: 120,
                                  height: 120,
                                  child: FlutterLogo(),
                                ),
                              ),
                              Positioned(
                                left: 16,
                                top: 114,
                                child: Container(
                                  width: 43,
                                  height: 43,
                                  child: FlutterLogo(),
                                ),
                              ),
                              Positioned(
                                left: 65,
                                top: 100,
                                child: Container(
                                  width: 35,
                                  height: 35,
                                  child: FlutterLogo(),
                                ),
                              ),
                              Positioned(
                                left: 12,
                                top: -4,
                                child: Container(
                                  width: 96,
                                  height: 96,
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: -2.50,
                                        top: -0.07,
                                        child: Container(
                                          width: 101.29,
                                          height: 96.87,
                                          child: Stack(
                                            children: [
                                              Positioned(
                                                left: 34.50,
                                                top: 0.07,
                                                child: Container(
                                                  width: 32,
                                                  height: 96,
                                                  child: FlutterLogo(),
                                                ),
                                              ),
                                              Positioned(
                                                left: 0.10,
                                                top: 48.07,
                                                child: Transform(
                                                  transform: Matrix4.identity()
                                                    ..translate(0.0, 0.0)
                                                    ..rotateZ(-1.26),
                                                  child: Container(
                                                    width: 32,
                                                    height: 96,
                                                    child: FlutterLogo(),
                                                  ),
                                                ),
                                              ),
                                              Positioned(
                                                left: 35.30,
                                                top: 96.87,
                                                child: Transform(
                                                  transform: Matrix4.identity()
                                                    ..translate(0.0, 0.0)
                                                    ..rotateZ(-2.51),
                                                  child: Container(
                                                    width: 32,
                                                    height: 96,
                                                    child: FlutterLogo(),
                                                  ),
                                                ),
                                              ),
                                              Positioned(
                                                left: 92.10,
                                                top: 77.67,
                                                child: Transform(
                                                  transform: Matrix4.identity()
                                                    ..translate(0.0, 0.0)
                                                    ..rotateZ(2.51),
                                                  child: Container(
                                                    width: 32,
                                                    height: 96,
                                                    child: FlutterLogo(),
                                                  ),
                                                ),
                                              ),
                                              Positioned(
                                                left: 91.30,
                                                top: 17.67,
                                                child: Transform(
                                                  transform: Matrix4.identity()
                                                    ..translate(0.0, 0.0)
                                                    ..rotateZ(1.26),
                                                  child: Container(
                                                    width: 32,
                                                    height: 96,
                                                    child: FlutterLogo(),
                                                  ),
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 22.01,
                                        top: -4.78,
                                        child: Transform(
                                          transform: Matrix4.identity()
                                            ..translate(0.0, 0.0)
                                            ..rotateZ(0.33),
                                          child: Container(
                                            width: 83.20,
                                            height: 83.20,
                                            child: FlutterLogo(),
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 89,
                        top: 0,
                        child: Container(
                          width: 120,
                          height: 200,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 80,
                                child: Container(
                                  width: 120,
                                  height: 120,
                                  child: FlutterLogo(),
                                ),
                              ),
                              Positioned(
                                left: 52.86,
                                top: 100.30,
                                child: Transform(
                                  transform: Matrix4.identity()
                                    ..translate(0.0, 0.0)
                                    ..rotateZ(2.62),
                                  child: Container(
                                    width: 57,
                                    height: 57,
                                    child: Stack(
                                      children: [
                                        Positioned(
                                          left: 9.02,
                                          top: 0,
                                          child: Container(
                                            width: 38.95,
                                            height: 24.70,
                                            child: Stack(
                                              children: [
                                                Positioned(
                                                  left: 1.42,
                                                  top: 4.27,
                                                  child: Container(
                                                    width: 2.37,
                                                    height: 2.37,
                                                    decoration: ShapeDecoration(
                                                      color: Color(0xFFFB5D66),
                                                      shape: OvalBorder(),
                                                    ),
                                                  ),
                                                ),
                                                Positioned(
                                                  left: 9.02,
                                                  top: 6.65,
                                                  child: Container(
                                                    width: 2.37,
                                                    height: 2.37,
                                                    decoration: ShapeDecoration(
                                                      color: Color(0xFFFB5D66),
                                                      shape: OvalBorder(),
                                                    ),
                                                  ),
                                                ),
                                                Positioned(
                                                  left: 15.20,
                                                  top: 9.50,
                                                  child: Container(
                                                    width: 2.37,
                                                    height: 2.37,
                                                    decoration: ShapeDecoration(
                                                      color: Color(0xFFFB5D66),
                                                      shape: OvalBorder(),
                                                    ),
                                                  ),
                                                ),
                                                Positioned(
                                                  left: 35.62,
                                                  top: 15.20,
                                                  child: Container(
                                                    width: 2.37,
                                                    height: 2.37,
                                                    decoration: ShapeDecoration(
                                                      color: Color(0xFFFB5D66),
                                                      shape: OvalBorder(),
                                                    ),
                                                  ),
                                                ),
                                                Positioned(
                                                  left: 36.57,
                                                  top: 19,
                                                  child: Container(
                                                    width: 2.37,
                                                    height: 2.37,
                                                    decoration: ShapeDecoration(
                                                      color: Color(0xFFFB5D66),
                                                      shape: OvalBorder(),
                                                    ),
                                                  ),
                                                ),
                                                Positioned(
                                                  left: 6.17,
                                                  top: 18.05,
                                                  child: Container(
                                                    width: 2.37,
                                                    height: 2.37,
                                                    decoration: ShapeDecoration(
                                                      color: Color(0xFFFB5D66),
                                                      shape: OvalBorder(),
                                                    ),
                                                  ),
                                                ),
                                                Positioned(
                                                  left: 6.65,
                                                  top: 22.32,
                                                  child: Container(
                                                    width: 2.37,
                                                    height: 2.37,
                                                    decoration: ShapeDecoration(
                                                      color: Color(0xFFFB5D66),
                                                      shape: OvalBorder(),
                                                    ),
                                                  ),
                                                ),
                                                Positioned(
                                                  left: 0,
                                                  top: 7.12,
                                                  child: Container(
                                                    width: 2.85,
                                                    height: 2.85,
                                                    decoration: ShapeDecoration(
                                                      color: Color(0xFFFB5D66),
                                                      shape: OvalBorder(),
                                                    ),
                                                  ),
                                                ),
                                                Positioned(
                                                  left: 31.35,
                                                  top: 0,
                                                  child: Container(
                                                    width: 2.37,
                                                    height: 2.37,
                                                    decoration: ShapeDecoration(
                                                      color: Color(0xFFFB5D66),
                                                      shape: OvalBorder(),
                                                    ),
                                                  ),
                                                ),
                                                Positioned(
                                                  left: 35.62,
                                                  top: 0.47,
                                                  child: Container(
                                                    width: 2.37,
                                                    height: 2.37,
                                                    decoration: ShapeDecoration(
                                                      color: Color(0xFFFB5D66),
                                                      shape: OvalBorder(),
                                                    ),
                                                  ),
                                                ),
                                              ],
                                            ),
                                          ),
                                        ),
                                      ],
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 12,
                                top: 0,
                                child: Container(
                                  width: 96,
                                  height: 96,
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 0,
                                        top: 0,
                                        child: Container(
                                          width: 96,
                                          height: 96,
                                          child: FlutterLogo(),
                                        ),
                                      ),
                                      Positioned(
                                        left: 0,
                                        top: 0,
                                        child: Container(
                                          width: 96,
                                          height: 96,
                                          child: FlutterLogo(),
                                        ),
                                      ),
                                      Positioned(
                                        left: 0,
                                        top: 0,
                                        child: Container(
                                          width: 96,
                                          height: 96,
                                          child: FlutterLogo(),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 0,
                                top: 101.77,
                                child: Transform(
                                  transform: Matrix4.identity()
                                    ..translate(0.0, 0.0)
                                    ..rotateZ(-0.52),
                                  child: Container(
                                    width: 31.53,
                                    height: 30.94,
                                    child: Stack(
                                      children: [
                                        Positioned(
                                          left: 0,
                                          top: 0,
                                          child: Container(
                                            width: 31.53,
                                            height: 30.94,
                                            child: FlutterLogo(),
                                          ),
                                        ),
                                        Positioned(
                                          left: 0,
                                          top: 0,
                                          child: Container(
                                            width: 31.53,
                                            height: 30.94,
                                            child: FlutterLogo(),
                                          ),
                                        ),
                                        Positioned(
                                          left: 0,
                                          top: 0,
                                          child: Container(
                                            width: 31.53,
                                            height: 30.94,
                                            child: FlutterLogo(),
                                          ),
                                        ),
                                      ],
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 114.99,
                                top: 101,
                                child: Transform(
                                  transform: Matrix4.identity()
                                    ..translate(0.0, 0.0)
                                    ..rotateZ(3.12),
                                  child: Container(
                                    width: 65,
                                    height: 65,
                                    child: FlutterLogo(),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 334,
                        top: 9,
                        child: Container(
                          width: 120,
                          height: 200,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 80,
                                child: Container(
                                  width: 120,
                                  height: 120,
                                  child: FlutterLogo(),
                                ),
                              ),
                              Positioned(
                                left: 38,
                                top: 118,
                                child: Container(
                                  width: 82,
                                  height: 82,
                                  child: FlutterLogo(),
                                ),
                              ),
                              Positioned(
                                left: 12,
                                top: 146,
                                child: Container(
                                  width: 54,
                                  height: 54,
                                  child: FlutterLogo(),
                                ),
                              ),
                              Positioned(
                                left: 32.91,
                                top: -12,
                                child: Transform(
                                  transform: Matrix4.identity()
                                    ..translate(0.0, 0.0)
                                    ..rotateZ(0.35),
                                  child: Container(
                                    width: 96,
                                    height: 96,
                                    child: Stack(
                                      children: [
                                        Positioned(
                                          left: 0,
                                          top: 0,
                                          child: Container(
                                            width: 96,
                                            height: 96,
                                            child: FlutterLogo(),
                                          ),
                                        ),
                                        Positioned(
                                          left: 0,
                                          top: 0,
                                          child: Container(
                                            width: 96,
                                            height: 96,
                                            child: FlutterLogo(),
                                          ),
                                        ),
                                        Positioned(
                                          left: 0,
                                          top: 0,
                                          child: Container(
                                            width: 96,
                                            height: 96,
                                            child: FlutterLogo(),
                                          ),
                                        ),
                                      ],
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 20,
                                top: 87,
                                child: Container(
                                  width: 41,
                                  height: 41,
                                  child: FlutterLogo(),
                                ),
                              ),
                              Positioned(
                                left: 71.12,
                                top: 91,
                                child: Transform(
                                  transform: Matrix4.identity()
                                    ..translate(0.0, 0.0)
                                    ..rotateZ(0.26),
                                  child: Container(
                                    width: 39.10,
                                    height: 39.10,
                                    child: FlutterLogo(),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: -78,
                                top: 29,
                                child: Container(
                                  width: 120,
                                  height: 200,
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 0,
                                        top: 80,
                                        child: Container(
                                          width: 120,
                                          height: 120,
                                          child: FlutterLogo(),
                                        ),
                                      ),
                                      Positioned(
                                        left: 31,
                                        top: 100,
                                        child: Container(
                                          width: 30,
                                          height: 30,
                                          child: FlutterLogo(),
                                        ),
                                      ),
                                      Positioned(
                                        left: 69.32,
                                        top: 89,
                                        child: Transform(
                                          transform: Matrix4.identity()
                                            ..translate(0.0, 0.0)
                                            ..rotateZ(0.26),
                                          child: Container(
                                            width: 93.95,
                                            height: 93.95,
                                            child: FlutterLogo(),
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 64,
                                        top: 92,
                                        child: Container(
                                          width: 21,
                                          height: 21,
                                          child: FlutterLogo(),
                                        ),
                                      ),
                                      Positioned(
                                        left: 17,
                                        top: 0,
                                        child: Container(
                                          width: 96,
                                          height: 96,
                                          child: Stack(
                                            children: [
                                              Positioned(
                                                left: 0,
                                                top: 0,
                                                child: Container(
                                                  width: 96,
                                                  height: 96,
                                                  child: FlutterLogo(),
                                                ),
                                              ),
                                              Positioned(
                                                left: 0,
                                                top: 0,
                                                child: Container(
                                                  width: 96,
                                                  height: 96,
                                                  child: FlutterLogo(),
                                                ),
                                              ),
                                              Positioned(
                                                left: 0,
                                                top: 0,
                                                child: Container(
                                                  width: 96,
                                                  height: 96,
                                                  child: FlutterLogo(),
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 217.57,
                top: 405,
                child: Container(
                  width: 176.43,
                  height: 210,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 176.43,
                          height: 210,
                          decoration: ShapeDecoration(
                            color: Color(0xFFFFCF86),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(10),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 19.75,
                        top: 17.22,
                        child: Container(
                          width: 139.05,
                          height: 127.78,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 15.30,
                                top: 0,
                                child: Container(
                                  width: 123.74,
                                  height: 111.32,
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 0,
                                        top: 0,
                                        child: Container(
                                          width: 44.48,
                                          height: 45.49,
                                          child: Stack(
                                            children: [
                                              Positioned(
                                                left: 26.11,
                                                top: 0,
                                                child: Container(
                                                  width: 18.37,
                                                  height: 34.60,
                                                  child: Stack(
                                                    children: [
                                                      Positioned(
                                                        left: 0,
                                                        top: 0,
                                                        child: Container(
                                                          width: 18.37,
                                                          height: 34.60,
                                                          child: Stack(),
                                                        ),
                                                      ),
                                                    ],
                                                  ),
                                                ),
                                              ),
                                              Positioned(
                                                left: -0,
                                                top: 9.14,
                                                child: Container(
                                                  width: 34.50,
                                                  height: 36.35,
                                                  child: Stack(
                                                    children: [
                                                      Positioned(
                                                        left: 0,
                                                        top: 0,
                                                        child: Container(
                                                          width: 34.50,
                                                          height: 36.35,
                                                          child: Stack(),
                                                        ),
                                                      ),
                                                    ],
                                                  ),
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 85.38,
                                        top: 80.78,
                                        child: Container(
                                          width: 38.36,
                                          height: 30.54,
                                          child: Stack(
                                            children: [
                                              Positioned(
                                                left: 0,
                                                top: 10.45,
                                                child: Container(
                                                  width: 33.31,
                                                  height: 20.09,
                                                  child: Stack(
                                                    children: [
                                                      Positioned(
                                                        left: 0,
                                                        top: 0,
                                                        child: Container(
                                                          width: 33.31,
                                                          height: 20.09,
                                                          child: Stack(),
                                                        ),
                                                      ),
                                                    ],
                                                  ),
                                                ),
                                              ),
                                              Positioned(
                                                left: 4.92,
                                                top: 0,
                                                child: Container(
                                                  width: 33.44,
                                                  height: 20.21,
                                                  child: Stack(
                                                    children: [
                                                      Positioned(
                                                        left: 0,
                                                        top: 0,
                                                        child: Container(
                                                          width: 33.44,
                                                          height: 20.21,
                                                          child: Stack(),
                                                        ),
                                                      ),
                                                    ],
                                                  ),
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 0.69,
                                top: 4.78,
                                child: Container(
                                  width: 133,
                                  height: 123,
                                  clipBehavior: Clip.antiAlias,
                                  decoration: BoxDecoration(),
                                  child: FlutterLogo(),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 17.43,
                        top: 161,
                        child: SizedBox(
                          width: 143,
                          height: 32,
                          child: Text(
                            '알람 설정',
                            style: TextStyle(
                              color: Color(0xFFFDF9F3),
                              fontSize: 30,
                              fontFamily: 'Freesentation',
                              fontWeight: FontWeight.w600,
                              height: 0.03,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            
              // 챗봇 선택
              Positioned(
                left: 20,
                top: 448,
                child: GestureDetector(
                  onTap: () {
                    // 클릭 시 실행할 네비게이션 동작
                    Navigator.push(
                      context,
                      MaterialPageRoute(
                          builder: (context) => FigmaToCode_3()), // NextPage로 이동
                    );
                  },
                  child: Container(
                    width: 176.43,
                    height: 167,
                    decoration: ShapeDecoration(
                      color: Color(0xFFFEB18F),
                      shape: RoundedRectangleBorder(
                        borderRadius: BorderRadius.circular(10),
                      ),
                    ),
                    child: Stack(
                      children: [
                        Positioned(
                          left: 0,
                          top: -1.53,
                          child: Container(
                            width: 176,
                            height: 97.68,
                            decoration: ShapeDecoration(
                              image: DecorationImage(
                                image: AssetImage('images/kakao_login.png'),
                                fit: BoxFit.fill,
                              ),
                              shape: RoundedRectangleBorder(
                                  borderRadius: BorderRadius.circular(9)),
                            ),
                          ),
                        ),
                        Positioned(
                          left: 9,
                          top: 118,
                          child: SizedBox(
                            width: 143,
                            height: 32,
                            child: Text(
                              '시니랑 대화',
                              style: TextStyle(
                                color: Color(0xFFFDF9F3),
                                fontSize: 30,
                                fontFamily: 'Freesentation',
                                fontWeight: FontWeight.w600,
                                height: 0.03,
                              ),
                            ),
                          ),
                        ),
                      ],
                    ),
                  ),
                ),
              ),
              // 챗봇 선택 끝

              Positioned(
                left: 217.57,
                top: 218,
                child: Container(
                  width: 176.43,
                  height: 167,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 176.43,
                          height: 167,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 176.43,
                                  height: 167,
                                  decoration: ShapeDecoration(
                                    color: Color(0xFFFA6E5A),
                                    shape: RoundedRectangleBorder(
                                      borderRadius: BorderRadius.circular(10),
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 11.43,
                                top: 111,
                                child: SizedBox(
                                  width: 143,
                                  height: 32,
                                  child: Text(
                                    '개인정보 설정',
                                    style: TextStyle(
                                      color: Color(0xFFFDF9F3),
                                      fontSize: 30,
                                      fontFamily: 'Freesentation',
                                      fontWeight: FontWeight.w600,
                                      height: 0.03,
                                    ),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 29.43,
                        top: 9,
                        child: Container(
                          width: 118,
                          height: 85,
                          clipBehavior: Clip.antiAlias,
                          decoration: BoxDecoration(),
                          child: FlutterLogo(),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 19,
                top: 217,
                child: Container(
                  width: 176.43,
                  height: 210,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 176.43,
                          height: 210,
                          decoration: ShapeDecoration(
                            color: Color(0xFF6BB2B2),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(10),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 9,
                        child: Container(
                          width: 176,
                          height: 129,
                          clipBehavior: Clip.antiAlias,
                          decoration: BoxDecoration(),
                          child: FlutterLogo(),
                        ),
                      ),
                      Positioned(
                        left: 8,
                        top: 156,
                        child: SizedBox(
                          width: 143,
                          height: 32,
                          child: Text(
                            '산책 하기',
                            style: TextStyle(
                              color: Color(0xFFFDF9F3),
                              fontSize: 30,
                              fontFamily: 'Freesentation',
                              fontWeight: FontWeight.w600,
                              height: 0.03,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}
